[workspace]
members = [ "crates/cli",
    "crates/helpers",
    # "crates/cli",
    # "crates/web",
    "crates/roc",
]

resolver = "2"

[workspace.package]
authors = ["Luke Boswell"]
edition = "2021"
license = "UPL-1.0"
repository = "https://github.com/lukewilliamboswell/roc-experiment-js-dom"
version = "0.0.1"

[workspace.dependencies]
