[package]
authors = ["Luke Boswell"]
edition = "2021"
name = "roc-dom"
version = "0.0.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.95"
roc_std = { git = "https://github.com/roc-lang/roc.git" }
wee_alloc = "0.4.5"

[dependencies.web-sys]
version = "0.3.72"
features = ['Document', 'Element', 'HtmlElement', 'Node', 'Window']

[build-dependencies]
build-target = "0.4"
