[package]
name = "cli"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
description.workspace = true

[dependencies]
roc = { path = "../roc" }
roc_std = { workspace = true}
